language: csharp
solution: docnet.sln
mono: none
dotnet: 2.1.300
script:
 - cd src
 - dotnet restore
 - dotnet test Docnet.Tests.Unit/
 - dotnet test Docnet.Tests.Integration/
 - dotnet build -c Release